name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and run Docker Compose
      run: |
        timeout 30s docker-compose up --abort-on-container-exit || echo "Job timed out after 50 seconds"
        docker-compose down
      env:
        SECRET_KEY: ${{secrets.SECRET_KEY}}

    - name: Run Django migrations
      run: python manage.py migrate
    - name: Collect static files
      run: python manage.py collectstatic --noinput

    - name: Run tests with Pytest
      run: |
        python manage.py test shop.tests.test_models
        python manage.py test shop.tests.test_views

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_KEY }}
        heroku_app_name: "online-shop2"
        heroku_email: "dgorpinuk50@gmail.com"
        buildpack: "heroku/python"
